# Fix CRMView
sed -i 's/const permissions = user?.permissions?.\[.\{1,10\}\];//g' src/views/CRMView.tsx
sed -i 's/const isReadonly = permissions?.readonly === true || user?.role === .viewer. || (user?.roles?.includes(.viewer.) && !user?.roles?.includes(.admin.) && !user?.roles?.includes(.manager.));//g' src/views/CRMView.tsx
sed -i 's/const canEdit = user?.roles?.includes(.admin.) || (permissions ? (permissions.edit !== false && !isReadonly) : !isReadonly);/const userRoles = user?.roles || [user?.role || "viewer"]; const hasFullAccess = userRoles.includes("admin"); const isReadonly = !hasFullAccess \&\& userRoles.some((role: string) => user.permissions?.[role]?.readonly === true); const canEdit = hasFullAccess || (!isReadonly \&\& userRoles.some((role: string) => { const p = user.permissions?.[role]; return p ? p.edit !== false : true; }));/g' src/views/CRMView.tsx
sed -i 's/const canDelete = user?.roles?.includes(.admin.) || (permissions ? (permissions.delete !== false && !isReadonly) : !isReadonly);/const canDelete = hasFullAccess || (!isReadonly \&\& userRoles.some((role: string) => { const p = user.permissions?.[role]; return p ? p.delete !== false : true; }));/g' src/views/CRMView.tsx

# Fix GestionView
sed -i 's/const permissions = user?.permissions?.\[.\{1,10\}\];//g' src/views/GestionView.tsx
sed -i 's/const isReadonly = permissions?.readonly === true || user?.role === .viewer. || (user?.roles?.includes(.viewer.) && !user?.roles?.includes(.admin.));//g' src/views/GestionView.tsx
sed -i 's/const canEdit = user?.roles?.includes(.admin.) || (permissions ? (permissions.edit !== false && !isReadonly) : !isReadonly);/const userRoles = user?.roles || [user?.role || "viewer"]; const hasFullAccess = userRoles.includes("admin"); const isReadonly = !hasFullAccess \&\& userRoles.some((role: string) => user.permissions?.[role]?.readonly === true); const canEdit = hasFullAccess || (!isReadonly \&\& userRoles.some((role: string) => { const p = user.permissions?.[role]; return p ? p.edit !== false : true; }));/g' src/views/GestionView.tsx
sed -i 's/const canDelete = user?.roles?.includes(.admin.) || (permissions ? (permissions.delete !== false && !isReadonly) : !isReadonly);/const canDelete = hasFullAccess || (!isReadonly \&\& userRoles.some((role: string) => { const p = user.permissions?.[role]; return p ? p.delete !== false : true; }));/g' src/views/GestionView.tsx

# Fix LabView
sed -i 's/const permissions = user?.permissions?.\[.\{1,10\}\];//g' src/views/LabView.tsx
sed -i 's/const isReadonly = permissions?.readonly === true || user?.role === .viewer. || (user?.roles?.includes(.viewer.) && !user?.roles?.includes(.admin.));//g' src/views/LabView.tsx
sed -i 's/const canEdit = user?.roles?.includes(.admin.) || (permissions ? (permissions.edit !== false && !isReadonly) : !isReadonly);/const userRoles = user?.roles || [user?.role || "viewer"]; const hasFullAccess = userRoles.includes("admin"); const isReadonly = !hasFullAccess \&\& userRoles.some((role: string) => user.permissions?.[role]?.readonly === true); const canEdit = hasFullAccess || (!isReadonly \&\& userRoles.some((role: string) => { const p = user.permissions?.[role]; return p ? p.edit !== false : true; }));/g' src/views/LabView.tsx
sed -i 's/const canDelete = user?.roles?.includes(.admin.) || (permissions ? (permissions.delete !== false && !isReadonly) : !isReadonly);/const canDelete = hasFullAccess || (!isReadonly \&\& userRoles.some((role: string) => { const p = user.permissions?.[role]; return p ? p.delete !== false : true; }));/g' src/views/LabView.tsx

# Fix SchoolView
sed -i 's/const permissions = user?.permissions?.\[.\{1,10\}\];//g' src/views/SchoolView.tsx
sed -i 's/const isReadonly = permissions?.readonly === true || user?.role === .viewer. || (user?.roles?.includes(.viewer.) && !user?.roles?.includes(.admin.));//g' src/views/SchoolView.tsx
sed -i 's/const canEdit = user?.roles?.includes(.admin.) || (permissions ? (permissions.edit !== false && !isReadonly) : !isReadonly);/const userRoles = user?.roles || [user?.role || "viewer"]; const hasFullAccess = userRoles.includes("admin"); const isReadonly = !hasFullAccess \&\& userRoles.some((role: string) => user.permissions?.[role]?.readonly === true); const canEdit = hasFullAccess || (!isReadonly \&\& userRoles.some((role: string) => { const p = user.permissions?.[role]; return p ? p.edit !== false : true; }));/g' src/views/SchoolView.tsx
sed -i 's/const canDelete = user?.roles?.includes(.admin.) || (permissions ? (permissions.delete !== false && !isReadonly) : !isReadonly);/const canDelete = hasFullAccess || (!isReadonly \&\& userRoles.some((role: string) => { const p = user.permissions?.[role]; return p ? p.delete !== false : true; }));/g' src/views/SchoolView.tsx
